"""empty message

Revision ID: e84e555deb29
Revises: 28be90ad7721
Create Date: 2026-04-29 09:30:26.628282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84e555deb29'
down_revision = '28be90ad7721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'conta', ['conta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conta_id')

    # ### end Alembic commands ###
